name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: RuboCop Lint
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.5'
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run RuboCop
      run: bundle exec rubocop

  test:
    needs: lint
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.0'
          - '3.3.0'
          - '3.2.3'
          - '3.0.0'
          - '2.7.2'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
